# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

q_target <- function(x) {
    .Call(`_MC_q_target`, x)
}

colVars <- function(mat) {
    .Call(`_MC_colVars`, mat)
}

importance_sampling_std <- function(n) {
    .Call(`_MC_importance_sampling_std`, n)
}

rejection_sampling <- function(n) {
    .Call(`_MC_rejection_sampling`, n)
}

sir_sampling <- function(m, n_resample) {
    .Call(`_MC_sir_sampling`, m, n_resample)
}

riemann_estimator <- function(samples) {
    .Call(`_MC_riemann_estimator`, samples)
}

comparison <- function(n_reps, n_samples) {
    .Call(`_MC_comparison`, n_reps, n_samples)
}

