# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EM_mix <- function(y, p0, lambda0, mu0, tol = 1e-6, max_iter = 1000L) {
    .Call(`_EM_EM_mix`, y, p0, lambda0, mu0, tol, max_iter)
}

rcpparma_hello_world <- function() {
    .Call(`_EM_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_EM_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_EM_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_EM_rcpparma_bothproducts`, x)
}

