# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bisection <- function(a, b, x, tol = 1e-6, max_iter = 1000L) {
    .Call(`_Optimization_bisection`, a, b, x, tol, max_iter)
}

newton <- function(theta0, x, tol = 1e-6, max_iter = 1000L) {
    .Call(`_Optimization_newton`, theta0, x, tol, max_iter)
}

fisher_scoring <- function(theta0, x, tol = 1e-6, max_iter = 1000L) {
    .Call(`_Optimization_fisher_scoring`, theta0, x, tol, max_iter)
}

secant <- function(theta0, theta1, x, tol = 1e-6, max_iter = 1000L) {
    .Call(`_Optimization_secant`, theta0, theta1, x, tol, max_iter)
}

logistic_predict <- function(X, beta) {
    .Call(`_Optimization_logistic_predict`, X, beta)
}

logistic_lik <- function(X, response, beta) {
    .Call(`_Optimization_logistic_lik`, X, response, beta)
}

multi_newton <- function(X, y, tol = 1e-6, max_iter = 1000L) {
    .Call(`_Optimization_multi_newton`, X, y, tol, max_iter)
}

score <- function(beta, X, y) {
    .Call(`_Optimization_score`, beta, X, y)
}

hessian <- function(beta, X, y) {
    .Call(`_Optimization_hessian`, beta, X, y)
}

