# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_adaptive_mcmc_chain <- function(u_initial_r, u_observed_r, noise_std, domain_length, t_obs, D_prior_mean_log, D_prior_sd_log, rho_prior_mean_log, rho_prior_sd_log, grid_size = 100L, dt = 0.01, num_iterations = 2000L, burnin = 1000L, initial_logD_prop_sd = 0.1, initial_logrho_prop_sd = 0.1, target_acceptance = 0.4, seed = 0L) {
    .Call(`_mcmc1dRDE_run_adaptive_mcmc_chain`, u_initial_r, u_observed_r, noise_std, domain_length, t_obs, D_prior_mean_log, D_prior_sd_log, rho_prior_mean_log, rho_prior_sd_log, grid_size, dt, num_iterations, burnin, initial_logD_prop_sd, initial_logrho_prop_sd, target_acceptance, seed)
}

simulate_pde_cpp <- function(u0, D, rho, domain_length, dt, t_end, grid_size = -1L) {
    .Call(`_mcmc1dRDE_simulate_pde_cpp`, u0, D, rho, domain_length, dt, t_end, grid_size)
}

