// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_adaptive_mcmc_chain
List run_adaptive_mcmc_chain(const NumericVector& u_initial_r, const NumericVector u_observed_r, double noise_std, double domain_length, double t_obs, double D_prior_mean_log, double D_prior_sd_log, double rho_prior_mean_log, double rho_prior_sd_log, int grid_size, double dt, int num_iterations, int burnin, double initial_logD_prop_sd, double initial_logrho_prop_sd, double target_acceptance, unsigned int seed);
RcppExport SEXP _mcmc1dRDE_run_adaptive_mcmc_chain(SEXP u_initial_rSEXP, SEXP u_observed_rSEXP, SEXP noise_stdSEXP, SEXP domain_lengthSEXP, SEXP t_obsSEXP, SEXP D_prior_mean_logSEXP, SEXP D_prior_sd_logSEXP, SEXP rho_prior_mean_logSEXP, SEXP rho_prior_sd_logSEXP, SEXP grid_sizeSEXP, SEXP dtSEXP, SEXP num_iterationsSEXP, SEXP burninSEXP, SEXP initial_logD_prop_sdSEXP, SEXP initial_logrho_prop_sdSEXP, SEXP target_acceptanceSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type u_initial_r(u_initial_rSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type u_observed_r(u_observed_rSEXP);
    Rcpp::traits::input_parameter< double >::type noise_std(noise_stdSEXP);
    Rcpp::traits::input_parameter< double >::type domain_length(domain_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type t_obs(t_obsSEXP);
    Rcpp::traits::input_parameter< double >::type D_prior_mean_log(D_prior_mean_logSEXP);
    Rcpp::traits::input_parameter< double >::type D_prior_sd_log(D_prior_sd_logSEXP);
    Rcpp::traits::input_parameter< double >::type rho_prior_mean_log(rho_prior_mean_logSEXP);
    Rcpp::traits::input_parameter< double >::type rho_prior_sd_log(rho_prior_sd_logSEXP);
    Rcpp::traits::input_parameter< int >::type grid_size(grid_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type num_iterations(num_iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< double >::type initial_logD_prop_sd(initial_logD_prop_sdSEXP);
    Rcpp::traits::input_parameter< double >::type initial_logrho_prop_sd(initial_logrho_prop_sdSEXP);
    Rcpp::traits::input_parameter< double >::type target_acceptance(target_acceptanceSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(run_adaptive_mcmc_chain(u_initial_r, u_observed_r, noise_std, domain_length, t_obs, D_prior_mean_log, D_prior_sd_log, rho_prior_mean_log, rho_prior_sd_log, grid_size, dt, num_iterations, burnin, initial_logD_prop_sd, initial_logrho_prop_sd, target_acceptance, seed));
    return rcpp_result_gen;
END_RCPP
}
// simulate_pde_cpp
NumericVector simulate_pde_cpp(NumericVector u0, double D, double rho, double domain_length, double dt, double t_end, int grid_size);
RcppExport SEXP _mcmc1dRDE_simulate_pde_cpp(SEXP u0SEXP, SEXP DSEXP, SEXP rhoSEXP, SEXP domain_lengthSEXP, SEXP dtSEXP, SEXP t_endSEXP, SEXP grid_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u0(u0SEXP);
    Rcpp::traits::input_parameter< double >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type domain_length(domain_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type t_end(t_endSEXP);
    Rcpp::traits::input_parameter< int >::type grid_size(grid_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_pde_cpp(u0, D, rho, domain_length, dt, t_end, grid_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mcmc1dRDE_run_adaptive_mcmc_chain", (DL_FUNC) &_mcmc1dRDE_run_adaptive_mcmc_chain, 17},
    {"_mcmc1dRDE_simulate_pde_cpp", (DL_FUNC) &_mcmc1dRDE_simulate_pde_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_mcmc1dRDE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
